# Site settings
title: Code, Code, Code by zhuts
motto: Exploring various aspects of programming, one snippet at a time
email: zhutsell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zhuts.github.io/index.html" # the base hostname & protocol for your site
twitter_username:
github_username:  zhuts

# Build settings
markdown: kramdown
